//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOTPiSP_Laba1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF3C3C3C")]
        public global::System.Windows.Media.SolidColorBrush BgDarkColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["BgDarkColor"]));
            }
            set {
                this["BgDarkColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF696969")]
        public global::System.Windows.Media.SolidColorBrush BgMidColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["BgMidColor"]));
            }
            set {
                this["BgMidColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF7C7C7C")]
        public global::System.Windows.Media.SolidColorBrush BgLightColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["BgLightColor"]));
            }
            set {
                this["BgLightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF4C4C4C")]
        public global::System.Windows.Media.SolidColorBrush BgButtonsColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["BgButtonsColor"]));
            }
            set {
                this["BgButtonsColor"] = value;
            }
        }
    }
}
